# -*- coding: utf-8 -*-
"""Python Practice.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MxrQCU5ZluKO4Ee49gFP9-JUOXhxpkiu
"""

hello = "shri sabhariesh"
print(hello)

name=input("Enter your name: ")
print("hi", name)

import matplotlib.pyplot as plt
plt.plot([1,2],[3,4])
plt.show