# -*- coding: utf-8 -*-
"""Python Practice 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vBnOanAa4PONoIu7WUi-jt7orUtdYwbS

DAY 2
"""

x=100
type(x)

x = 654*6734
print(x)

x=3.14
type(x)

x='simplilearn'
type(x)

x=[14, 67, 9]
print(x)

type(x)

print(x[1])

x= (4,8,6)
print(x)

type(x)

"""Arithmetic Operations

"""

x=10
y=20
result=x+y
print(result)

result=x-y
print(result)

result=x*y
print(result)

result=x/y
print(result)

result=x//y
print(result)

result=x%y
print(result)

"""String Operations

"""

var="Shri Sabhariesh"
print(var[3])

print(var[0:3])

print(var[1:4])

print(var[6:])